### ISSUE TITLE
 Swift Compiler Error (Xcode): Instance method 'throttle(for:scheduler:latest:)' requires that 'DispatchQueue' conform to 'Scheduler' /Users/lxj/Documents/dev/as_space/tspapp/ios/Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift:227:13

### ISSUE THREAD

**Issue by li-xiaojun** [aws-amplify/aws-appsync-realtime-client-ios#125]
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Instance method 'throttle(for:scheduler:latest:)' requires that 'DispatchQueue' conform to 'Scheduler'
/Users/lxj/Documents/dev/as_space/tspapp/ios/Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/ConnectionProvider/AppsyncRealtimeConnection/RealtimeConnectionProvider.swift:227:13

Uncategorized (Xcode): Command CompileC failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by royjit** [comment]
Hi @li-xiaojun Thank you for reaching us. Could you please provide us with the following information to help debug further:

- AppSyncRealtimeClient version used
- Cocodpods Podfile / Package.swift information
- Xcode version used
- Does clean build solves the issue?
