### ISSUE TITLE
Starscream dependency

### ISSUE THREAD

**Issue by rissicay** [aws-amplify/aws-appsync-realtime-client-ios#16]
Hi,

Is there any reason why Starscream is locked to 3.0.6? In my local I have custom PodSpec which allows me to compile against 3.1.0 (clash with other pod). All seems to work (haven't put it thru QA yet

Is it possible to get a version bump for Starscream?

**Comment by lawmicha** [comment]
Hi @rissicay, thanks for opening this issue, i believe at the time the version was 3.0.6. We can take a look at upgrading to 3.1.0 and make sure things are working. https://github.com/daltoniam/Starscream/releases mentions that 3.1.0 was just to add Swift 5 and Xcode 10.2 support. 

Can you provide more details to problem you are facing or use case? Are you trying to use Amplify APIPlugin or AppSync SDK and add Starscream dependency in your podfile?

**Comment by lawmicha** [comment]
Hi @rissicay this has been released in 1.2.0 and PR has been merged, could you give it a try and let us know if you are still seeing any issues?

**Comment by lawmicha** [comment]
Closing this now, feel free to open another issue if something is not working for you
