### ISSUE TITLE
Cartfile should match pod dependency: pod "Starscream", "~> 3.1.0"

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/aws-appsync-realtime-client-ios#23]

**Comment by wooj2** [comment]
* Bare minimum:
  * Update our release process, so that when we update a dependency on starscream, we also update it in the cart file.
* stretch goal
  * Update build/release process to  automatically check the two files are in sync

**Comment by palpatim** [comment]
Pending release of #29

**Comment by palpatim** [comment]
Released on https://github.com/aws-amplify/aws-appsync-realtime-client-ios/releases/tag/1.4.1
