### ISSUE TITLE
Please support disable log function.

### ISSUE THREAD

**Issue by SwiftyWang** [aws-amplify/aws-appsync-realtime-client-ios#31]
Currently, every time a new msg coming always print debug log.
```WebsocketDidReceiveMessage ......```
This log should be printed by StarscreamAdapter+Delegate
Please add a log flag to disable or enable logger.

**Comment by dabodamjan** [comment]
This is very distracting as usually a large amount of logs are generated. So It makes it hard to use any logs at all without searching for specific ones.

**Comment by jacobsapps** [comment]
Seconding this, if the LogLevel is set to `.error`, the lowest level, why is it giving us any information that isn't about errors?

**Comment by treystudio3a** [comment]
Any updates on this or suggestions for a temporary fix?

**Comment by afern247** [comment]
Any update on this? It's very annoying to debug something while a bunch of logs are being printed out that have nothing to do with it.

**Comment by aspearman** [comment]
Just came across this while trying to silence all these logs. Setting `Amplify.Logging.logLevel = .error` doesn't seem to have an effect as @jacobsapps has said. Even the [docs](https://docs.amplify.aws/start/getting-started/integrate/q/integration/ios/#configure-amplify-and-datastore) say this should work, which is misleading:
>Optionally, if you'd like to adjust the log level, you can do this by updating the Amplify.Logging.logLevel variable. For example, you can add the following line of code to the configureAmplify() function:
> `Amplify.Logging.logLevel = .info`

 This makes it much more difficult to find the logs I care about.

**Comment by lawmicha** [comment]
AppSyncRTClient's logging isn't controlled by Amplify.Logging, I think we would have to pass logLevel down perhaps statically to only log up to a defined log level. Currently it uses os_log. 

In this recent PR one of the busiest and unuseful log lines is removed here: https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/66/files#diff-b2b1007e258a4f4c98a074b1fec4007bf9e67e1aafcb053d9d832a6799d9e55a

**Comment by lawmicha** [comment]
This has been released in 1.8.0 https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/72
Amplify.Logging.logLevel will be passed down to AppSyncRealTimeClient's log level in https://github.com/aws-amplify/amplify-ios/pull/1637

**Comment by diegocstn** [comment]
Amplify [v1.20.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.20.0) consuming AppSyncRealTimeClient v1.8.0 has been released.
