### ISSUE TITLE
Found some memory leaks in instrument

### ISSUE THREAD

**Issue by zhouhao27** [aws-amplify/aws-appsync-realtime-client-ios#90]
I found some memory leaks when I run Instrument Leak check:

>    9 Starscream TCPTransport.connect(url:timeout:certificatePinning:) ../ios/Pods/Starscream/Sources/Transport/TCPTransport.swift:80
  10 Starscream protocol witness for Transport.connect(url:timeout:certificatePinning:) in conformance TCPTransport ../ios/Pods/<compiler-generated>:0
  11 Starscream WSEngine.start(request:) ../ios/Pods/Starscream/Sources/Engine/WSEngine.swift:67
  12 Starscream protocol witness for Engine.start(request:) in conformance WSEngine ../ios/Pods/<compiler-generated>:0
  13 Starscream WebSocket.connect() ../ios/Pods/Starscream/Sources/Starscream/WebSocket.swift:135
  14 AppSyncRealTimeClient closure #1 in StarscreamAdapter.connect(url:protocols:delegate:) ../ios/Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift:47
  15 AppSyncRealTimeClient thunk for @escaping @callee_guaranteed () -> () ../ios/Pods/<compiler-generated>:0

My version is 1.9.1. Any idea?

**Comment by lawmicha** [comment]
Hi @zhouhao27, thanks for briniging this to our attention. This package uses Starscream from https://github.com/daltoniam/Starscream . At version 1.9.1 https://github.com/aws-amplify/aws-appsync-realtime-client-ios/tree/1.9.1 I can see it uses 4.0.4
```
// In Package.swift
.package(url: "https://github.com/daltoniam/Starscream", .upToNextMinor(from: "4.0.4"))
``` 

From Starscreams releases, at this time 4.0.4 appears to be the latest version https://github.com/daltoniam/Starscream/tags 

I opened an issue over there: https://github.com/daltoniam/Starscream/issues/954

Do you have more details as to what you were doing while observing the memory leak? Any additional information like screenshots or code snippets that we can use to reproduce the problem?
