### ISSUE TITLE
Error while preparing release build

### ISSUE THREAD

**Issue by bhavik45** [aws-amplify/aws-appsync-realtime-client-ios#92]
I am using the below pods for AWS amplify services -

  pod 'Amplify'
  pod 'AWSAppSync'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AWSCognitoIdentityProvider'
  
It's working fine when I run the app in debug mode, but When I try to create a release build, the build is failing with the below error -
  **Instance method 'throttle(for:scheduler:latest:)' requires that 'DispatchQueue' conform to 'Scheduler'**
  
It's inside **AppSyncRealTimeClient -> RealtimeConnectionProvider -> subscribeToLimitExceededThrottle()**

For more investigation, I created a new project and added the above pods. It's giving me the same errors in that newly created project as well.

**Comment by lawmicha** [comment]
Hi @bhavik45, i couldn't reproduce this issue, I added the pods you mentioned and that generated Podfile.lock with `AppSyncRealTimeClient (1.10.0)`.

I'm using Xcode 13.4.1 which has IOS Deployment Target 15.5 when creating a new project. I see some related issues like https://github.com/groue/GRDB.swift/issues/1059 that talks about iOS 10 causing the problem. What is your Xcode version and iOS deployment target? Are you still seeing a problem?

**Comment by bhavik45** [comment]
@lawmicha I'm using Xcode 13 and for some reason, I have set the IOS Deployment Target to iOS 12. The project is developed with swift 5.

I'm still facing the same issue.

**Comment by ranjitDhiman1990** [comment]
Hi, I'm facing the same issue.

**Comment by bhavik45** [comment]
@lawmicha Please let me know if any update is there on this

**Comment by bhavik45** [comment]
@ranjitDhiman1990 I have found a workaround which is currently working for me. It's not a permanent solution but at least I am able to prepare build for now. 

Here is the workaround - 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
```

I would like to give the credit to the person who gave this answer but I lost the link.

**Comment by ranjitDhiman1990** [comment]
Thanks @bhavik45 , it also worked for me.

**Comment by uzairleo** [comment]
I am facing. the same issue but the workaround is not working for me @bhavik45

**Comment by li-xiaojun** [comment]
Swift Compiler Error (Xcode): Instance method 'throttle(for:scheduler:latest:)' requires that 'DispatchQueue' conform to 'Scheduler'

**Comment by royjit** [comment]
Hi, apologies for losing track on this issue. Are you still facing this in you release build? Please provide the exact version of xcode/iOS and any project specific configuration that will help us to debug the issue.
